task: train
task: error
# task: test
# task: "hyperparameter_optimize"
# task: equations
# task: equ_error
data:
  type: grid
  normal: ../data/grid/14_normal.csv
  normal: ../data/grid/14_state.csv
  # normal: ../data/grid/118_state.csv
  # normal: ../data/grid/14_simple.csv
  attack: ../data/grid/14_attack.csv
  ybus: ../data/grid/14_ybus.csv
  # ybus: ../data/grid/118_ybus.csv
  n_features: 117
  n_buses: 14
  mva_base: 100
  
model:
  hidden_size: 100
  layer_sizes: [40, 20, 10]
  n_layers: 2
  sequence_length: 10
  activation: leakyRelu
  profile_type: mean
#  profile_type: gmm
  dropout: 0
train:
  gpus: 4
  nodes: 1
  batch_size: 64
  epochs: 500
  lr: 0.1
  scale: [1, 1]
  regularization: 0.001
  num_samples: 20
  checkpoint: grid_14
  checkpoint_dir: checkpoint
  load_checkpoint: 0

  train_fraction: 0.5
  validate_fraction: 0.25
  find_error_fraction: 0.25
  loss: equation
  equation_name: grid