task: train
# task: error
# task: test
# task: "hyperparameter_optimize"
# task: equations
task: equ_error
data:
  type: grid
  normal: ../data/grid/14_normal.csv
  normal: ../data/grid/14_state.csv
  normal: ../data/grid/118_state.csv
  # normal: ../data/grid/14_simple.csv
  attack: ../data/grid/14_attack.csv
  ybus: ../data/grid/14_ybus.csv
  ybus: ../data/grid/118_ybus.csv
  n_features: 117
  n_buses: 118
model:
  type: autoencoder
  # type: prediction
  hidden_size: 20
  layer_sizes: [40, 20, 10]
  n_layers: 2
  activation: leakyRelu
  embedding_size: 10
  sequence_length: 1
  window_size: 1
  profile_type: mean
#  profile_type: gmm
  dropout: 0


train:
  n_workers: 3
  gpus: 4
  nodes: 1
  batch_size: 64
  epochs: 500
  lr: 0.1
  scale: [1, 1]
  regularization: 0.0017
#  regularization: 0.0053
  num_samples: 20
  checkpoint: grid_14
  checkpoint_dir: checkpoint
  load_checkpoint: 0

  train_fraction: 0.3
#  train_fraction: 0.1
#  train_fraction: 0.8
  invariant_fraction: 0.2
  validate_fraction: 0.1
  find_error_fraction: 0.4
#  validation_frequency: 1
  loss: equation
  equation_name: grid
  type: prediction
  max_gmm_components: 5
  invariants: grid