task: train_localize
task: localize
# task: error
# task: test
# task: "hyperparameter_optimize"
# task: equations
# task: equ_error
# task: attack_generation
data: 
  type: grid
  normal: ../data/grid/14_normal.csv
  # normal: ../data/grid/14_continuous_admittance.csv
  # normal: ../data/grid/14_cube_sampling.csv
  # normal: ../data/grid//14_lines_out.csv
  # normal: ../data/grid/14_2_lines_out.csv
  # normal: ../data/grid/14_attack_base.csv
  attack: ../data/grid/14_perfect_fdia_train.csv
  test: ../data/grid/14_perfect_fdia.csv
  # attack: ../data/grid/14_attacks_2.csv
  # attack: ../data/grid/14_normal.csv
  # attack: ../data/grid/14_continuous_admittance.csv
  # attack: ../data/grid/14_line_1_out.csv
  attack_base: ../data/grid/14_continuous_admittance.csv
  types: ../data/grid/14_types.csv
  ybus: ../data/grid/14_ybus.csv
  n_buses: 14
  mva_base: 100
  powerworld: 0

attack:
  bias: 0.2
  network_parameter_error: 0.1
  state_variable_error: 0.07
  # network_parameter_error: 0
  # state_variable_error: 0
model:
  hidden_size: 32
  layer_sizes: [40, 20, 10]
  n_layers: 2
  sequence_length: 10
  activation: relu
  profile_type: mean
#  profile_type: gmm
  dropout: 0.767
  threshold: 6.78
  graph: 1
  n_heads: 5
  n_stacks: 2
  n_iters: 2

train:
  cuda: 1
  gpus: 4
  nodes: 1
  batch_size: 64
  epochs: 100
  lr: 0.001
  fraction: 0.5
  # Cube sampling 
  # lr: 0.01
  scale: [0.1, 1]
  average: micro
  regularization: 0.000074845134550496
  max_norm: 0.7
  num_samples: 20
  checkpoint: duel
  # checkpoint: test
  checkpoint_dir: checkpoint
  load_checkpoint: 1
  tuned: localization
  train_fraction: 0.7
  validate_fraction: 0.3
  find_error_fraction: 0.25
  # train_fraction: 0
  # validate_fraction: 0
  # find_error_fraction: 1
  equation_name: grid
  physics: 1
  population_train: 0