task: train_pinn
task: train_localize
task: localize
# task: error
# task: test
# task: "hyperparameter_optimize"
# task: equations
# task: equ_error
# task: attack_generation
data: 
  type: grid
  normal: ../data/grid/14_normal.csv
  # normal: ../data/grid/14_continuous_admittance.csv
  # normal: ../data/grid/14_cube_sampling.csv
  normal: ../data/grid//14_lines_out.csv
  # normal: ../data/grid/14_2_lines_out.csv
  # normal: ../data/grid/14_attack_base.csv
  normal: ../data/grid/14_perfect_fdia_train.csv
  attack: ../data/grid/14_perfect_fdia_train.csv
  test: ../data/grid/14_imperfect_fdia.csv
  # attack: ../data/grid/14_attacks_2.csv
  # attack: ../data/grid/14_normal.csv
  # attack: ../data/grid/14_continuous_admittance.csv
  # attack: ../data/grid/14_line_1_out.csv
  attack_base: ../data/grid/14_continuous_admittance.csv
  types: ../data/grid/14_types.csv
  ybus: ../data/grid/14_ybus.csv
  n_buses: 14
  mva_base: 100
  powerworld: 0

attack:
  bias: 0.2
  network_parameter_error: 0.1
  state_variable_error: 0.07
  # network_parameter_error: 0
  # state_variable_error: 0
model:
  hidden_size: 64
  layer_sizes: [40, 20, 10]
  n_layers: 3
  sequence_length: 10
  activation: relu
  profile_type: mean
#  profile_type: gmm
  dropout: 0.56
  threshold: 6.78
  graph: 1
  n_stacks: 4


train:
  cuda: 1
  gpus: 4
  nodes: 1
  batch_size: 64
  epochs: 200
  lr: 0.00079
  max_norm: 1
  # Cube sampling 
  # lr: 0.01
  scale: [0.1, 1]
  average: micro
  regularization: 0.001
  num_samples: 20
  checkpoint: grid_14_normal_topology
  checkpoint: test
  checkpoint_dir: checkpoint/
  tune_checkpoint: checkpoint/TorchTrainer_2024-02-10_11-13-26
  load_checkpoint: 1
  tuned: local
  fraction: 0.01
  train_fraction: 0.8
  validate_fraction: 0.2
  find_error_fraction: 0.25
  # train_fraction: 0
  # validate_fraction: 0
  # find_error_fraction: 1
  equation_name: grid
  physics: 1
  population_train: 0  