#task: "train"
task: "error"
data:
#  normal: "../Datasets/SWAT/SWaT_Dataset_Normal_v0.csv"
  normal: "../Datasets/SWAT/First_Hour_2015.csv"
  n_features: 51

model:
  hidden_layers: [100, 100, 100]
  activation: "leakyRelu"
  sequence_length: 5
  window_size: 1

train:
  batch_size: 256
  epochs: 50
  lr: 0.0005
  regularization: 0.00001
  checkpoint: swat_2015
  tensorboard: False
  train_fraction: 0.5
  validate_fraction: 0.1
  find_error_fraction: 0.2
  validation_frequency: 20
