task: train
task: error
task: test
# task: "hyperparameter_optimize"
# task: equations
data:
  type: swat
  normal: ../data/SWAT/SWaT_Dataset_Normal_v0.csv
  attack: ../data/SWAT/SWaT_Dataset_Attack_modified.csv
  n_features: 51

model:
  type: autoencoder
  type: prediction
  hidden_size: 50
  layer_sizes: [64, 32, 16, 8]
  n_layers: 1
  activation: tanh
  embedding_size: -1
  sequence_length: 10
  window_size: 8
  profile_type: mean
  #  profile_type: gmm
  dropout: 0


train:
  n_workers: 3
  gpus: 4
  nodes: 1
  batch_size: 64
  epochs: 100
  lr: 0.1
  scale: [1, 0.0005, .01, .01, 1, 10]
  regularization: 0.0017
#  regularization: 0.0053
  num_samples: 20
  checkpoint: swat_sensors
  # checkpoint: swat_autoencoder_equ
  checkpoint_dir: checkpoint
  load_checkpoint: 0

  train_fraction: 0.3
#  train_fraction: 0.1
#  train_fraction: 0.8
  invariant_fraction: 0.2
  validate_fraction: 0.1
  find_error_fraction: 0.4
#  validation_frequency: 1
  loss: equation
  equation_name: swat
  max_gmm_components: 5
  distribution_threshold: 1.2
  event_predicate_error: 0.01
  gamma: 0.9
#  gamma: 0.7
#  theta: 0.1
  theta: 0.08
  max_depth: 2
  min_confidence: 0.8
  type: invariants
  type: prediction
  invariants: swat_reduced
#  invariants: swat_benchmark
