#task: train
#task: error
task: test
#task: predicates
#task: invariants
data:
  normal: ../Datasets/SWAT/SWaT_Dataset_Normal_v0.csv
#  normal: ../Datasets/SWAT/First_Hour_2015.csv
#  normal: C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/SWaT_Dataset_Normal_v0.csv
#  normal: C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/First_Hour_2015.csv
  attack: ../Datasets/SWAT/SWaT_Dataset_Attack_v0.csv
#  attack: C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/SWaT_Dataset_Attack_v0.csv
  n_features: 51

model:
  hidden_layers: [100, 100]
  activation: leakyRelu
  embedding_size: 0
  sequence_length: 5
  window_size: 20

train:
  n_workers: 8
  batch_size: 64
  epochs: 1
  lr: 0.0005
  regularization: 0.00001
  checkpoint: swat_2015_full
  load_checkpoint: 0

  tensorboard: 1
  train_fraction: 0.4
  validate_fraction: 0.1
  find_error_fraction: 0.5
  validation_frequency: 10

  max_gmm_components: 5
  distribution_threshold: 1.2
  event_predicate_error: 0.0001
  gamma: 0.6
  theta: 0.1
  max_depth: 3
  type: invariants