task: "train"
#task: "error"
#task: "test"
#task: "plot"
data:
  normal: "../Datasets/SWAT/SWaT_Dataset_Normal_v0.csv"
#  normal: "../Datasets/SWAT/First_Hour_2015.csv"
#  normal: "C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/SWaT_Dataset_Normal_v0.csv"
#  normal: "C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/First_Hour_2015.csv"
#  attack: "../Datasets/SWAT/SWaT_Dataset_Attack_v0.csv"
  attack: "C:/Users/mland/OneDrive - Georgia Institute of Technology/Documents/Datasets/SWAT/SWaT_Dataset_Attack_v0.csv"
  n_features: 51

model:
  hidden_layers: [100, 100]
  activation: "leakyRelu"
  embedding_size: 10
  sequence_length: 25
  window_size: 200

train:
  n_workers: 1
  batch_size: 64
  epochs: 1000
  lr: 0.0005
  regularization: 0.00001
  checkpoint: "swat_2015_full"
  tensorboard: true
  train_fraction: 0.4
  validate_fraction: 0.1
  find_error_fraction: 0.3
  validation_frequency: 100
